import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const tzdbVersion = process.argv[2] || '2025b';

async function main(): Promise<void> {
  const url = `https://raw.githubusercontent.com/eggert/tz/${tzdbVersion}/zone.tab`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch zone.tab for tzdb ${tzdbVersion}: ${response.status} ${response.statusText}`);
  }

  const text = await response.text();
  const lines = text.split('\n');
  const zoneSet = new Set<string>();

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const parts = line.split('\t');
    if (parts.length >= 3) {
      const zone = parts[2]!.trim();
      if (zone) {
        zoneSet.add(zone);
      }
    }
  }

  // Ensure UTC is included
  zoneSet.delete('UTC');
  const sortedZones = Array.from(zoneSet).sort((a, b) => a.localeCompare(b));
  const allZones = ['UTC', ...sortedZones];

  // Validate all zones with Intl.DateTimeFormat
  for (const zone of allZones) {
    try {
      new Intl.DateTimeFormat('en-US', { timeZone: zone });
    } catch (err) {
      throw new Error(`Timezone ${zone} rejected by Intl.DateTimeFormat: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const targetPath = resolve(__dirname, '../src/timezones.ts');

  const content = `// GENERATED by scripts/generateTimezones.ts from tzdb ${tzdbVersion}/zone.tab — do not edit.
export const TZDB_VERSION = '${tzdbVersion}';
export const WORKSPACE_TIMEZONES = [
${allZones.map((z) => `  ${JSON.stringify(z)},`).join('\n')}
] as const;
export type WorkspaceTimezone = (typeof WORKSPACE_TIMEZONES)[number];
export const WORKSPACE_TIMEZONE_SET: ReadonlySet<string> = new Set(WORKSPACE_TIMEZONES);
`;

  writeFileSync(targetPath, content, 'utf-8');
  console.log(`Successfully generated ${allZones.length} timezones from tzdb ${tzdbVersion} into src/timezones.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

