export const SLUG_CHECK_LIMITER = Symbol('SLUG_CHECK_LIMITER');
export const WORKSPACE_WRITE_LIMITER = Symbol('WORKSPACE_WRITE_LIMITER');
export const MEMBER_CANDIDATE_LIMITER = Symbol('MEMBER_CANDIDATE_LIMITER');

